### PR TITLE
QOL Changes

### PR DESCRIPTION
**Pull request by CoolSpy3**
This PR creates 3 small changes that I didn't think each required their own PRs:
1) Allows instructions at the start of lines rather than requiring an indent for highlighting to work
2) Fixes the rep prefixes to highlight the instructions which will be repeated
3) Adds highlighting for the qword size prefix (and the ptr postfix-keyword)

### CODE REVIEW

**Comment by maziac** [comment]
Actually I just included a PR for the x86 assembly language, so I'm not that uptodate on the syntax.
Couple of questions:
1. What is QOL?
2. Why should instructions start at the start of the line?

**Comment by CoolSpy3** [comment]
1. QOL stands for Quality of Life (referring to changes which are fairly minor and are meant to polish up existing functionality). I honestly just didn't feel like each of these required a separate PR and felt like this was the best way to sum it up. If you want, I can change it to a longer-form title.
2. It's not a requirement, but in the current project I'm working on, there are a few instances where it just doesn't make sense to indent the instructions, and because the instruction regexes require a preceding whitespace character, it fails to apply the syntax highlighting (example below).

no_indent

**Comment by maziac** [comment]
Does nasm allow instructions starting at the start of line?

This contradicts with labels without colons.

**Comment by CoolSpy3** [comment]
Yes; NASM (by default) only allows labels without colons if they're followed by another assembler directive (ex. `db`). It also doesn't allow labels which are also instructions (i.e. I can't make a label named `add`)

**Comment by maziac** [comment]
Can you remove the change regarding opposes at the start of the line.
It would interfere with the z80 syntax highlighting, I.e. labels that appear to be mnemonics in x86 would be highlighted.
The other changes should be fine.

FYI I‘m thinking of dividing code lense features and the syntax highlighting in the future. Having 3 separate extensions:
- asm code lens wo syntax highlighting 
- x86/nasm syntax highlighting 
- z80 syntax highlighting 

When separated it becomes easier to add assembler specific changes.

**Comment by CoolSpy3** [comment]
Done! I look forward to seeing the assembler specific extensions in the future. Good luck :D

**Comment by maziac** [comment]
I'm currently thinking about the names for the language IDs for the 2 extensions for z80 an x86.
z80 will probably be called "sjasmplus" which is the main supported assembler.
For x86 I'm not sure. Do you have any suggestion? As all the grammar is from different people I'm not even sure if a specific assembler (NASM) is supported or if it is some general x86 syntax. Do you know?

**Comment by CoolSpy3** [comment]
After rereading the syntax, I don't see any specific regex for x86 assemblers (although it does look like there's some overlap with SjASMPlus). I'm aware of four main x86 assemblers: GNU Assembler, FASM, MASM, and NASM, although [Wikipedia lists some others as well](https://en.wikipedia.org/wiki/Comparison_of_assemblers#x86_assemblers). Personally, however, I've only used NASM (and even then, I only started working with it over the summer).

**Comment by maziac** [comment]
Thanks for info.

**Pull request merged**
